/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */

 plugins {
     kotlin("jvm") version "1.8.21"
     id("io.ktor.plugin") version "2.3.1"
 }

 repositories {
     mavenCentral()
 }


 dependencies {
     implementation(files("/selekt/selekt-java/build/libs/selekt-java-0.20.0-SNAPSHOT.jar"))
     implementation(files("/selekt/selekt-api/build/libs/selekt-api-0.20.0-SNAPSHOT.jar"))
     implementation("com.code-intelligence:jazzer-junit:0.16.1")
     implementation("com.code-intelligence:jazzer-api:0.16.1")
     implementation("org.mockito.kotlin:mockito-kotlin:5.+")
 }

 application {
    mainClass.set("com.forallsecure.selekt_fuzz.SelektSimpleSQLQueryFuzzer")
 }

 ktor {
     fatJar {
         archiveFileName.set("fat.jar")
     }
 }
