/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */

 plugins {
     id("com.github.johnrengelman.shadow") version "8.1.1"
     id("java")
 }

 repositories {
     mavenCentral()
 }

 dependencies {
     implementation(files("/selekt/selekt-android/build/libs/selekt-android-0.19.0-SNAPSHOT-sources.jar"))
     testImplementation("com.code-intelligence:jazzer-api:0.16.1")
     testImplementation("org.mockito:mockito-core:3.+")
 }
